services:
  # DB service (shared configuration)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Dev-specific postgres config
  postgres_dev:
    extends: postgres
    container_name: postgres_dev
    environment:
      POSTGRES_DB: curatedotfun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # dev persists volumes, so you don't lose your setup
    profiles: ["dev"]

  # Test-specific postgres config
  postgres_test:
    extends: postgres
    container_name: postgres_test
    environment:
      POSTGRES_DB: test
    ports:
      - "54321:5432"
    # No volume for a fresh DB each time
    profiles: ["test"]

  # handles data migration and database seeding
  db-migrate-dev:
    image: oven/bun:latest
    working_dir: /app/packages/shared-db
    volumes:
      - ./:/app
      - node_modules_cache:/app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_dev:5432/curatedotfun
    depends_on:
      postgres_dev:
        condition: service_healthy
    command: sh -c "bunx drizzle-kit migrate"
    profiles: ["dev"]

  db-seed-dev:
    extends: db-migrate-dev
    command: sh -c "bun ./scripts/seed-dev.ts"
    profiles: ["dev"]

  # Test-specific initialization
  db-init-test:
    extends: db-init
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_test:5432/test
    depends_on:
      postgres_test:
        condition: service_healthy
    command: sh -c "bun add -g pnpm && pnpm install && pnpm run db:migrate && pnpm run db:seed:test"
    profiles: ["test"]

  # Application service
  app:
    build:
      context: . 
      dockerfile: apps/api/Dockerfile
    depends_on:
      postgres_prod:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres_prod:5432/curatedotfun
      NODE_ENV: production
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"
    profiles: ["prod"] # we can run the app profile to test a production run

volumes:
  postgres_data:
  node_modules_cache: # Add persistent volume for node_modules
